name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 14.0.2
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      macos:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web
      windows:
        default_package: geolocator_windows
      linux:
        default_package: geolocator_linux

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface: 
    path: ../geolocator_platform_interface
  geolocator_android: 
    path: ../geolocator_android
  geolocator_apple: 
    path: ../geolocator_apple
  geolocator_web: 
    path: ../geolocator_web
  geolocator_windows: 
    path: ../geolocator_windows
  geolocator_linux: 
    path: ../geolocator_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.1.8
